--Database Type    :Oracle
--Schema           :schema
--Create date      :Fri Jan 18 10:18:46 KST 2019
--Tool version     :3.3.0.1



DROP TABLE EXAM_MANAGER.BOARD1 CASCADE CONSTRAINTS PURGE;


--
--BOARD1   (TABLE)
--
CREATE TABLE EXAM_MANAGER.BOARD1(
  SEQ NUMBER(10,0) NOT NULL,
  CNT NUMBER(10,0) NOT NULL,
  CONTENT VARCHAR2(255 BYTE),
  REGDATE DATE,
  TITLE VARCHAR2(255 BYTE),
  WRITER VARCHAR2(255 BYTE)
)
TABLESPACE TS_EXAM_MANAGER
 PCTFREE 10
 INITRANS 1
 MAXTRANS 255
 STORAGE
 (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
 ) MONITORING;
