--Database Type    :Oracle
--Schema           :schema
--Create date      :Fri Jan 18 10:18:46 KST 2019
--Tool version     :3.3.0.1



DROP TABLE EXAM_MANAGER.BOARD CASCADE CONSTRAINTS PURGE;


--
--BOARD   (TABLE)
--
CREATE TABLE EXAM_MANAGER.BOARD(
  NO NUMBER NOT NULL,
  TITLE VARCHAR2(50 BYTE),
  WRITER VARCHAR2(30 BYTE),
  CONTENT VARCHAR2(4000 BYTE),
  FNAME VARCHAR2(200 BYTE),
  REG_DATE DATE,
  VIEWCNT NUMBER,
  B_REF NUMBER,
  B_LEVEL NUMBER,
  B_STEP NUMBER,
  KEY VARCHAR2(200 BYTE)
)
TABLESPACE TS_EXAM_MANAGER
 PCTFREE 10
 INITRANS 1
 MAXTRANS 255
 STORAGE
 (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
 ) MONITORING;
