--Database Type    :Oracle
--Schema           :schema
--Create date      :Fri Jan 18 10:18:46 KST 2019
--Tool version     :3.3.0.1



DROP TABLE EXAM_MANAGER.BONUS CASCADE CONSTRAINTS PURGE;


--
--BONUS   (TABLE)
--
CREATE TABLE EXAM_MANAGER.BONUS(
  ENAME VARCHAR2(10 BYTE),
  COMM NUMBER,
  JOB VARCHAR2(9 BYTE),
  SAL NUMBER
)
TABLESPACE TS_EXAM_MANAGER
 PCTFREE 10
 INITRANS 1
 MAXTRANS 255
 STORAGE
 (
  BUFFER_POOL DEFAULT
 ) MONITORING;
