--Database Type    :Oracle
--Schema           :schema
--Create date      :Fri Jan 18 10:18:46 KST 2019
--Tool version     :3.3.0.1



DROP TABLE EXAM_MANAGER.CODEMNG CASCADE CONSTRAINTS PURGE;


--
--CODEMNG   (TABLE)
--
CREATE TABLE EXAM_MANAGER.CODEMNG(
  CDNO VARCHAR2(5 BYTE) NOT NULL,
  CDLVL NUMBER(1,0) NOT NULL,
  UPCD VARCHAR2(5 BYTE) NOT NULL,
  CDNAME VARCHAR2(20 BYTE) NOT NULL,
  INSUSER VARCHAR2(20 BYTE) NOT NULL,
  INSDATE VARCHAR2(8 BYTE) NOT NULL,
  USEYN VARCHAR2(1 BYTE) DEFAULT 'Y'
)
TABLESPACE TS_EXAM_MANAGER
 PCTFREE 10
 INITRANS 1
 MAXTRANS 255
 STORAGE
 (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
 ) MONITORING;

COMMENT ON TABLE EXAM_MANAGER.CODEMNG IS '内靛包府';
COMMENT ON COLUMN EXAM_MANAGER.CODEMNG.CDNO IS '内靛锅龋';