/*---------------------------------------------
-- 오브젝트명: EXAM_MANAGER.DEPT
-- 생성일자 : 2018-06-27 17:39:26.0
-- 상태: VALID
---------------------------------------------*/
CREATE TABLE EXAM_MANAGER.DEPT(
  LOC VARCHAR2(13 BYTE),
  DEPTNO NUMBER(2,0),
  DNAME VARCHAR2(14 BYTE)
)
TABLESPACE TS_EXAM_MANAGER
 PCTFREE 10
 INITRANS 1
 MAXTRANS 255
 STORAGE
 (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
 ) MONITORING;

COMMENT ON TABLE EXAM_MANAGER.DEPT IS '부서';

COMMENT ON COLUMN EXAM_MANAGER.DEPT.LOC IS '위치';

COMMENT ON COLUMN EXAM_MANAGER.DEPT.DEPTNO IS '부서코드';

COMMENT ON COLUMN EXAM_MANAGER.DEPT.DNAME IS '부서명';

ALTER TABLE EXAM_MANAGER.DEPT ADD CONSTRAINT PK_DEPT PRIMARY KEY (DEPTNO);
