--Database Type    :Oracle
--Schema           :schema
--Create date      :Fri Jan 18 10:18:46 KST 2019
--Tool version     :3.3.0.1



DROP TABLE EXAM_MANAGER.EMP CASCADE CONSTRAINTS PURGE;


--
--EMP   (TABLE)
--
CREATE TABLE EXAM_MANAGER.EMP(
  ENAME VARCHAR2(10 BYTE),
  COMM NUMBER(7,2),
  HIREDATE DATE,
  EMPNO NUMBER(4,0) NOT NULL,
  MGR NUMBER(4,0),
  JOB VARCHAR2(9 BYTE),
  DEPTNO NUMBER(2,0),
  SAL NUMBER(7,2)
)
TABLESPACE TS_EXAM_MANAGER
 PCTFREE 10
 INITRANS 1
 MAXTRANS 255
 STORAGE
 (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
 ) MONITORING;

COMMENT ON TABLE EXAM_MANAGER.EMP IS '사원';
COMMENT ON COLUMN EXAM_MANAGER.EMP.ENAME IS '사원명';