/*---------------------------------------------
-- 오브젝트명: EXAM_MANAGER.EMP
-- 생성일자 : 2018-06-27 17:39:37.0
-- 상태: VALID
---------------------------------------------*/
CREATE TABLE EXAM_MANAGER.EMP(
  ENAME VARCHAR2(10 BYTE),
  COMM NUMBER(7,2),
  HIREDATE DATE,
  EMPNO NUMBER(4,0) NOT NULL,
  MGR NUMBER(4,0),
  JOB VARCHAR2(9 BYTE),
  DEPTNO NUMBER(2,0),
  SAL NUMBER(7,2)
)
TABLESPACE TS_EXAM_MANAGER
 PCTFREE 10
 INITRANS 1
 MAXTRANS 255
 STORAGE
 (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
 ) MONITORING;

COMMENT ON TABLE EXAM_MANAGER.EMP IS '사원';

COMMENT ON COLUMN EXAM_MANAGER.EMP.ENAME IS '사원명';

COMMENT ON COLUMN EXAM_MANAGER.EMP.HIREDATE IS '입사일';

COMMENT ON COLUMN EXAM_MANAGER.EMP.EMPNO IS '사원번호';

COMMENT ON COLUMN EXAM_MANAGER.EMP.JOB IS '직무';

COMMENT ON COLUMN EXAM_MANAGER.EMP.DEPTNO IS '부서코드';

COMMENT ON COLUMN EXAM_MANAGER.EMP.SAL IS '월급';

ALTER TABLE EXAM_MANAGER.EMP ADD CONSTRAINT PK_EMP PRIMARY KEY (EMPNO);

ALTER TABLE EXAM_MANAGER.EMP ADD CONSTRAINT FK_DEPTNO FOREIGN KEY (DEPTNO) REFERENCES "EXAM_MANAGER"."DEPT"(DEPTNO);
