--Database Type    :Oracle
--Schema           :schema
--Create date      :Fri Jan 18 10:18:46 KST 2019
--Tool version     :3.3.0.1



DROP TABLE EXAM_MANAGER.EMPLIST CASCADE CONSTRAINTS PURGE;


--
--EMPLIST   (TABLE)
--
CREATE TABLE EXAM_MANAGER.EMPLIST(
  EMPNO NUMBER(10,0) NOT NULL,
  COMM NUMBER(10,0) NOT NULL,
  DEPTNO NUMBER(10,0) NOT NULL,
  ENAME VARCHAR2(255 CHAR),
  HIREDATE DATE,
  JOB VARCHAR2(255 CHAR),
  MGR NUMBER(10,0) NOT NULL,
  SAL NUMBER(10,0) NOT NULL
)
TABLESPACE TS_EXAM_MANAGER
 PCTFREE 10
 INITRANS 1
 MAXTRANS 255
 STORAGE
 (
  BUFFER_POOL DEFAULT
 ) MONITORING;
