/*---------------------------------------------
-- 오브젝트명: EXAM_MANAGER.INITEMLIST
-- 생성일자 : 2018-08-13 10:56:42.0
-- 상태: VALID
---------------------------------------------*/
CREATE TABLE EXAM_MANAGER.INITEMLIST(
  ITEMCD VARCHAR2(5 BYTE) NOT NULL,
  INSITEMLISTCD VARCHAR2(10 BYTE),
  INSAMT NUMBER(5,0) NOT NULL,
  INSDATE VARCHAR2(8 BYTE) NOT NULL,
  INSUSER VARCHAR2(20 BYTE) NOT NULL
)
TABLESPACE TS_EXAM_MANAGER
 PCTFREE 10
 INITRANS 1
 MAXTRANS 255
 STORAGE
 (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
 ) MONITORING;

COMMENT ON TABLE EXAM_MANAGER.INITEMLIST IS '입고상품리스트';

COMMENT ON COLUMN EXAM_MANAGER.INITEMLIST.ITEMCD IS '상품코드(i)';

COMMENT ON COLUMN EXAM_MANAGER.INITEMLIST.INSITEMLISTCD IS '입고상품리스트코드(ii)';

COMMENT ON COLUMN EXAM_MANAGER.INITEMLIST.INSAMT IS '입고수량';

COMMENT ON COLUMN EXAM_MANAGER.INITEMLIST.INSDATE IS '입고일';

COMMENT ON COLUMN EXAM_MANAGER.INITEMLIST.INSUSER IS '등록자';

ALTER TABLE EXAM_MANAGER.INITEMLIST ADD CONSTRAINT SYS_C0013093 PRIMARY KEY (INSITEMLISTCD);

ALTER TABLE EXAM_MANAGER.INITEMLIST ADD CONSTRAINT SYS_C0013100 FOREIGN KEY (ITEMCD) REFERENCES "EXAM_MANAGER"."ITEMLIST"(ITEMCD);
