--Database Type    :Oracle
--Schema           :schema
--Create date      :Fri Jan 18 10:18:46 KST 2019
--Tool version     :3.3.0.1



DROP TABLE EXAM_MANAGER.INITEMLIST CASCADE CONSTRAINTS PURGE;


--
--INITEMLIST   (TABLE)
--
CREATE TABLE EXAM_MANAGER.INITEMLIST(
  ITEMCD VARCHAR2(5 BYTE) NOT NULL,
  INSITEMLISTCD VARCHAR2(10 BYTE),
  INSAMT NUMBER(5,0) NOT NULL,
  INSDATE VARCHAR2(8 BYTE) NOT NULL,
  INSUSER VARCHAR2(20 BYTE) NOT NULL
)
TABLESPACE TS_EXAM_MANAGER
 PCTFREE 10
 INITRANS 1
 MAXTRANS 255
 STORAGE
 (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
 ) MONITORING;

COMMENT ON TABLE EXAM_MANAGER.INITEMLIST IS '입고상품리스트';
COMMENT ON COLUMN EXAM_MANAGER.INITEMLIST.ITEMCD IS '상품코드(i)';