/*---------------------------------------------
-- 오브젝트명: EXAM_MANAGER.ITEMLIST
-- 생성일자 : 2018-08-13 10:56:42.0
-- 상태: VALID
---------------------------------------------*/
CREATE TABLE EXAM_MANAGER.ITEMLIST(
  ITEMCD VARCHAR2(5 BYTE) NOT NULL,
  ITEMNAME VARCHAR2(20 BYTE) NOT NULL,
  MADENMCD VARCHAR2(5 BYTE) NOT NULL,
  ITEMUNITCD VARCHAR2(5 BYTE),
  STOCKAMT NUMBER(8,0) DEFAULT 0 NOT NULL,
  STOCKYN VARCHAR2(1 BYTE) DEFAULT 'Y',
  INSUSER VARCHAR2(20 BYTE) NOT NULL,
  INSDATE VARCHAR2(8 BYTE) NOT NULL,
  USEYN VARCHAR2(1 BYTE),
  ITEMCLSCD VARCHAR2(5 BYTE)
)
TABLESPACE TS_EXAM_MANAGER
 PCTFREE 10
 INITRANS 1
 MAXTRANS 255
 STORAGE
 (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
 ) MONITORING;

COMMENT ON TABLE EXAM_MANAGER.ITEMLIST IS '상품리스트';

COMMENT ON COLUMN EXAM_MANAGER.ITEMLIST.ITEMCD IS '상품코드(i)';

COMMENT ON COLUMN EXAM_MANAGER.ITEMLIST.ITEMNAME IS '상품명';

COMMENT ON COLUMN EXAM_MANAGER.ITEMLIST.MADENMCD IS '제조사코드';

COMMENT ON COLUMN EXAM_MANAGER.ITEMLIST.ITEMUNITCD IS '단위코드';

COMMENT ON COLUMN EXAM_MANAGER.ITEMLIST.STOCKAMT IS '재고수량';

COMMENT ON COLUMN EXAM_MANAGER.ITEMLIST.STOCKYN IS 'stockYN';

COMMENT ON COLUMN EXAM_MANAGER.ITEMLIST.INSUSER IS '등록자';

COMMENT ON COLUMN EXAM_MANAGER.ITEMLIST.INSDATE IS '등록일';

COMMENT ON COLUMN EXAM_MANAGER.ITEMLIST.USEYN IS '사용여부';

COMMENT ON COLUMN EXAM_MANAGER.ITEMLIST.ITEMCLSCD IS '상품분류코드';

ALTER TABLE EXAM_MANAGER.ITEMLIST ADD CONSTRAINT SYS_C0013087 PRIMARY KEY (ITEMCD);
