--Database Type    :Oracle
--Schema           :schema
--Create date      :Fri Jan 18 10:18:46 KST 2019
--Tool version     :3.3.0.1



DROP TABLE EXAM_MANAGER.ITEMLIST CASCADE CONSTRAINTS PURGE;


--
--ITEMLIST   (TABLE)
--
CREATE TABLE EXAM_MANAGER.ITEMLIST(
  ITEMCD VARCHAR2(5 BYTE) NOT NULL,
  ITEMNAME VARCHAR2(20 BYTE) NOT NULL,
  MADENMCD VARCHAR2(5 BYTE) NOT NULL,
  ITEMUNITCD VARCHAR2(5 BYTE),
  STOCKAMT NUMBER(8,0) DEFAULT 0 NOT NULL,
  STOCKYN VARCHAR2(1 BYTE) DEFAULT 'Y',
  INSUSER VARCHAR2(20 BYTE) NOT NULL,
  INSDATE VARCHAR2(8 BYTE) NOT NULL,
  USEYN VARCHAR2(1 BYTE),
  ITEMCLSCD VARCHAR2(5 BYTE)
)
TABLESPACE TS_EXAM_MANAGER
 PCTFREE 10
 INITRANS 1
 MAXTRANS 255
 STORAGE
 (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
 ) MONITORING;

COMMENT ON TABLE EXAM_MANAGER.ITEMLIST IS '상품리스트';
COMMENT ON COLUMN EXAM_MANAGER.ITEMLIST.ITEMCD IS '상품코드(i)';