--Database Type    :Oracle
--Schema           :schema
--Create date      :Fri Jan 18 10:18:46 KST 2019
--Tool version     :3.3.0.1



DROP TABLE EXAM_MANAGER.MEMBERS CASCADE CONSTRAINTS PURGE;


--
--MEMBERS   (TABLE)
--
CREATE TABLE EXAM_MANAGER.MEMBERS(
  ID VARCHAR2(20 BYTE) NOT NULL,
  PWD VARCHAR2(15 BYTE) NOT NULL,
  NAME VARCHAR2(16 BYTE) NOT NULL,
  ADMIN VARCHAR2(15 BYTE) NOT NULL,
  ADDR VARCHAR2(50 BYTE),
  TEL VARCHAR2(20 BYTE),
  POINT NUMBER
)
TABLESPACE TS_EXAM_MANAGER
 PCTFREE 10
 INITRANS 1
 MAXTRANS 255
 STORAGE
 (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
 ) MONITORING;
