--Database Type    :Oracle
--Schema           :schema
--Create date      :Fri Jan 18 10:18:47 KST 2019
--Tool version     :3.3.0.1



DROP TABLE EXAM_MANAGER.OUTITEMLIST CASCADE CONSTRAINTS PURGE;


--
--OUTITEMLIST   (TABLE)
--
CREATE TABLE EXAM_MANAGER.OUTITEMLIST(
  ITEMCD VARCHAR2(5 BYTE) NOT NULL,
  USERINFODETAILCD VARCHAR2(10 BYTE) NOT NULL,
  OUTITEMLISTCD VARCHAR2(10 BYTE) NOT NULL,
  DELIVAMT NUMBER(5,0) NOT NULL,
  CHECKUSER VARCHAR2(20 BYTE),
  CHECKDATE VARCHAR2(8 BYTE),
  CHECKYN VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
  DELIVYN VARCHAR2(1 BYTE) DEFAULT 'N',
  DELIVCORPCD VARCHAR2(5 BYTE),
  DELIVNO VARCHAR2(10 BYTE),
  INSUSER VARCHAR2(20 BYTE),
  INSDATE VARCHAR2(8 BYTE)
)
TABLESPACE TS_EXAM_MANAGER
 PCTFREE 10
 INITRANS 1
 MAXTRANS 255
 STORAGE
 (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
 ) MONITORING;

COMMENT ON TABLE EXAM_MANAGER.OUTITEMLIST IS '출고상품리스트';
COMMENT ON COLUMN EXAM_MANAGER.OUTITEMLIST.ITEMCD IS '상품코드(i)';