--Database Type    :Oracle
--Schema           :schema
--Create date      :Fri Jan 18 10:18:47 KST 2019
--Tool version     :3.3.0.1



DROP TABLE EXAM_MANAGER.SALGRADE CASCADE CONSTRAINTS PURGE;


--
--SALGRADE   (TABLE)
--
CREATE TABLE EXAM_MANAGER.SALGRADE(
  GRADE NUMBER,
  LOSAL NUMBER,
  HISAL NUMBER
)
TABLESPACE TS_EXAM_MANAGER
 PCTFREE 10
 INITRANS 1
 MAXTRANS 255
 STORAGE
 (
  BUFFER_POOL DEFAULT
 ) MONITORING;
