--Database Type    :Oracle
--Schema           :schema
--Create date      :Fri Jan 18 10:18:47 KST 2019
--Tool version     :3.3.0.1



DROP TABLE EXAM_MANAGER."TEST" CASCADE CONSTRAINTS PURGE;


--
--TEST   (TABLE)
--
CREATE TABLE EXAM_MANAGER."TEST"(
  ENAME NUMBER(5,0) NOT NULL,
  COMM VARCHAR2(200 BYTE) NOT NULL,
  HIREDATE VARCHAR2(20 BYTE),
  EMPNO VARCHAR2(2000 BYTE) NOT NULL,
  MGR DATE DEFAULT SYSDATE,
  JOB NUMBER(5,0) DEFAULT 0,
  DEPTNO NUMBER(5,0) DEFAULT 0,
  SAL NUMBER(5,0) DEFAULT 0
)
TABLESPACE TS_EXAM_MANAGER
 PCTFREE 10
 INITRANS 1
 MAXTRANS 255
 STORAGE
 (
  BUFFER_POOL DEFAULT
 ) MONITORING;
