/*---------------------------------------------
-- 오브젝트명: EXAM_MANAGER.USERINFODETAIL
-- 생성일자 : 2018-08-09 10:37:54.0
-- 상태: VALID
---------------------------------------------*/
CREATE TABLE EXAM_MANAGER.USERINFODETAIL(
  ID VARCHAR2(20 BYTE) NOT NULL,
  USERINFODETAILCD VARCHAR2(10 BYTE),
  RELCD VARCHAR2(5 BYTE) NOT NULL,
  ADDRCD NUMBER(5,0) NOT NULL,
  ADDRNAME VARCHAR2(30 BYTE) NOT NULL,
  MOBILETELNO VARCHAR2(11 BYTE),
  HOMETELNO VARCHAR2(11 BYTE),
  INSUSER VARCHAR2(20 BYTE),
  INSDATE VARCHAR2(8 BYTE),
  USEYN VARCHAR2(1 BYTE),
  DELIVNAME VARCHAR2(20 BYTE) NOT NULL
)
TABLESPACE TS_EXAM_MANAGER
 PCTFREE 10
 INITRANS 1
 MAXTRANS 255
 STORAGE
 (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
 ) MONITORING;

COMMENT ON TABLE EXAM_MANAGER.USERINFODETAIL IS '회원상세정보';

COMMENT ON COLUMN EXAM_MANAGER.USERINFODETAIL.ID IS '아이디';

COMMENT ON COLUMN EXAM_MANAGER.USERINFODETAIL.USERINFODETAILCD IS '회원상세정보코드(u)';

COMMENT ON COLUMN EXAM_MANAGER.USERINFODETAIL.RELCD IS '관계코드';

COMMENT ON COLUMN EXAM_MANAGER.USERINFODETAIL.ADDRCD IS '우편번호';

COMMENT ON COLUMN EXAM_MANAGER.USERINFODETAIL.ADDRNAME IS '주소명';

COMMENT ON COLUMN EXAM_MANAGER.USERINFODETAIL.MOBILETELNO IS '휴대전화번호';

COMMENT ON COLUMN EXAM_MANAGER.USERINFODETAIL.HOMETELNO IS '집전화번호';

COMMENT ON COLUMN EXAM_MANAGER.USERINFODETAIL.INSUSER IS '등록자';

COMMENT ON COLUMN EXAM_MANAGER.USERINFODETAIL.INSDATE IS '등록일';

COMMENT ON COLUMN EXAM_MANAGER.USERINFODETAIL.USEYN IS '사용여부';

COMMENT ON COLUMN EXAM_MANAGER.USERINFODETAIL.DELIVNAME IS '수신자성명';

ALTER TABLE EXAM_MANAGER.USERINFODETAIL ADD CONSTRAINT SYS_C0012829 PRIMARY KEY (USERINFODETAILCD);

ALTER TABLE EXAM_MANAGER.USERINFODETAIL ADD CONSTRAINT SYS_C0012833 FOREIGN KEY (ID) REFERENCES "EXAM_MANAGER"."USERINFO"(ID);
