--Database Type    :Oracle
--Schema           :schema
--Create date      :Fri Jan 18 10:18:47 KST 2019
--Tool version     :3.3.0.1



DROP TABLE EXAM_MANAGER.USERINFO CASCADE CONSTRAINTS PURGE;


--
--USERINFO   (TABLE)
--
CREATE TABLE EXAM_MANAGER.USERINFO(
  ID VARCHAR2(20 BYTE) NOT NULL,
  PASS VARCHAR2(10 BYTE) NOT NULL,
  NAME VARCHAR2(20 BYTE) NOT NULL,
  INSDATE VARCHAR2(8 BYTE) NOT NULL,
  USEYN VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL
)
TABLESPACE TS_EXAM_MANAGER
 PCTFREE 10
 INITRANS 1
 MAXTRANS 255
 STORAGE
 (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
 ) MONITORING;

COMMENT ON TABLE EXAM_MANAGER.USERINFO IS '회원정보';
COMMENT ON COLUMN EXAM_MANAGER.USERINFO.ID IS '아이디';