--Database Type    :Oracle
--Schema           :schema
--Create date      :Fri Jan 18 10:18:47 KST 2019
--Tool version     :3.3.0.1



DROP TABLE EXAM_MANAGER.USERINFODETAIL CASCADE CONSTRAINTS PURGE;


--
--USERINFODETAIL   (TABLE)
--
CREATE TABLE EXAM_MANAGER.USERINFODETAIL(
  ID VARCHAR2(20 BYTE) NOT NULL,
  USERINFODETAILCD VARCHAR2(10 BYTE),
  RELCD VARCHAR2(5 BYTE) NOT NULL,
  ADDRCD NUMBER(5,0) NOT NULL,
  ADDRNAME VARCHAR2(30 BYTE) NOT NULL,
  MOBILETELNO VARCHAR2(11 BYTE),
  HOMETELNO VARCHAR2(11 BYTE),
  INSUSER VARCHAR2(20 BYTE),
  INSDATE VARCHAR2(8 BYTE),
  USEYN VARCHAR2(1 BYTE),
  DELIVNAME VARCHAR2(20 BYTE) NOT NULL
)
TABLESPACE TS_EXAM_MANAGER
 PCTFREE 10
 INITRANS 1
 MAXTRANS 255
 STORAGE
 (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
 ) MONITORING;

COMMENT ON TABLE EXAM_MANAGER.USERINFODETAIL IS '회원상세정보';
COMMENT ON COLUMN EXAM_MANAGER.USERINFODETAIL.ID IS '아이디';