--Database Type    :Oracle
--Schema           :schema
--Create date      :Fri Jan 18 10:18:47 KST 2019
--Tool version     :3.3.0.1



DROP TABLE EXAM_MANAGER.USERBASKET CASCADE CONSTRAINTS PURGE;


--
--USERBASKET   (TABLE)
--
CREATE TABLE EXAM_MANAGER.USERBASKET(
  ID VARCHAR2(20 BYTE) NOT NULL,
  ITEMCD VARCHAR2(5 BYTE) NOT NULL,
  USERBASKETCD VARCHAR2(10 BYTE) NOT NULL,
  PAYYN VARCHAR2(1 BYTE) DEFAULT 'N'
)
TABLESPACE TS_EXAM_MANAGER
 PCTFREE 10
 INITRANS 1
 MAXTRANS 255
 STORAGE
 (
  BUFFER_POOL DEFAULT
 ) MONITORING;

COMMENT ON TABLE EXAM_MANAGER.USERBASKET IS '장바구니';
COMMENT ON COLUMN EXAM_MANAGER.USERBASKET.ID IS '아이디';