@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\TABLE\BOARD.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\TABLE\BOARD1.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\TABLE\BONUS.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\TABLE\CODEMNG.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\TABLE\DEPT.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\TABLE\EMP.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\TABLE\EMPLIST.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\TABLE\INITEMLIST.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\TABLE\ITEMLIST.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\TABLE\MEMBER.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\TABLE\MEMBERS.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\TABLE\OUTITEMLIST.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\TABLE\SALGRADE.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\TABLE\TEST.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\TABLE\USERBASKET.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\TABLE\USERINFO.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\TABLE\USERINFODETAIL.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\INDEX\PK_EMP.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\INDEX\PK_DEPT.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\INDEX\SYS_C0013099.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\INDEX\SYS_C0012015.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\INDEX\SYS_C0012056.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\INDEX\SYS_C0013093.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\INDEX\SYS_C0012823.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\INDEX\SYS_C0012802.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\INDEX\SYS_C0012829.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\INDEX\SYS_C0016280.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\INDEX\SYS_C0013087.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\INDEX\SYS_C0012817.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\INDEX\SYS_C0014549.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\INDEX\SYS_C0016233.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\CONSTRAINT\PK_DEPT.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\CONSTRAINT\PK_EMP.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\CONSTRAINT\FK_DEPTNO.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\SEQUENCE\HIBERNATE_SEQUENCE.sql
@C:\Users\mnet-10\Documents\workspace-sts-3.9.4.RELEASE\Spring-Maven\DB\SEQUENCE\USERSEQ.sql
