--Database Type    :Oracle
--Schema           :schema
--Create date      :Fri Jan 18 10:18:47 KST 2019
--Tool version     :3.3.0.1



DROP SEQUENCE EXAM_MANAGER.HIBERNATE_SEQUENCE;


--
--HIBERNATE_SEQUENCE   (SEQUENCE)
--
CREATE SEQUENCE EXAM_MANAGER.HIBERNATE_SEQUENCE
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1
 NOMAXVALUE
 NOCYCLE
 CACHE 20
 NOORDER
;
